project:
  type: website

website:
  title: "Quarto Benchmarking Notes"
  navbar:
    left:
      - href: notes/index.qmd
        text: Index

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto